# Generated by Django 5.1.4 on 2026-09-03 06:55

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SeasonEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('from_status', models.CharField(max_length=32)),
                ('to_status', models.CharField(max_length=32)),
                ('note', models.TextField(blank=True)),
                ('payload', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'db_table': 'season_events',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField()),
                ('name_uz', models.CharField(max_length=120)),
                ('name_en', models.CharField(blank=True, max_length=120)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'tracks',
            },
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(unique=True)),
                ('name_uz', models.CharField(max_length=120)),
                ('name_en', models.CharField(blank=True, max_length=120)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('applications_open', 'Applications Open'), ('applications_closed', 'Applications Closed'), ('interview', 'Interview'), ('selection_finalized', 'Selection Finalized'), ('program_running', 'Program Running'), ('demo_day', 'Demo Day'), ('closed', 'Closed'), ('cancelled', 'Cancelled')], default='draft', max_length=32)),
                ('is_current', models.BooleanField(default=False)),
                ('is_alumni_published', models.BooleanField(default=False)),
                ('program_weeks', models.PositiveSmallIntegerField(default=10)),
                ('min_scores', models.PositiveSmallIntegerField(default=2)),
                ('scoring_weights', models.JSONField(blank=True, default=dict)),
                ('apply_opens_at', models.DateTimeField(blank=True, null=True)),
                ('apply_closes_at', models.DateTimeField(blank=True, null=True)),
                ('program_starts_at', models.DateTimeField(blank=True, null=True)),
                ('demo_day_at', models.DateTimeField(blank=True, null=True)),
                ('stats_override', models.JSONField(blank=True, default=dict, help_text='Faqat ushbu NavDU mavsumi raqamlari. Tashqi akselerator statistikasi taqiqlangan.')),
                ('curriculum', models.JSONField(blank=True, default=list)),
            ],
            options={
                'verbose_name': 'Mavsum',
                'verbose_name_plural': 'Mavsumlar',
                'db_table': 'seasons',
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_current', True)), fields=('is_current',), name='uq_season_single_current'), models.CheckConstraint(condition=models.Q(('min_scores__gte', 1), ('min_scores__lte', 10)), name='ck_season_min_scores_range')],
            },
        ),
    ]
