# Generated by Django 5.1.4 on 2026-09-03 06:55

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('channel', models.CharField(choices=[('email', 'Email'), ('inapp', 'Inapp')], max_length=10)),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField(blank=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('error', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'notifications',
            },
        ),
    ]
