# Generated by Django 5.1.15 on 2026-09-13 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layout', '0002_startup'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoFounderVacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startup_name', models.CharField(max_length=150, verbose_name='Startap Nomi')),
                ('startup_logo', models.CharField(default='🚀', max_length=20, verbose_name='Logo (Emoji)')),
                ('category', models.CharField(default='AI & EdTech', max_length=100, verbose_name='Soha / Kategoriya')),
                ('role_title', models.CharField(max_length=150, verbose_name='Qidirilayotgan Mutaxassis / Rol')),
                ('required_skills', models.JSONField(default=list, help_text='["React", "Python", "Figma"]', verbose_name='Kerakli Ko‘nikmalar (JSON massiv)')),
                ('description', models.TextField(verbose_name='Vakansiya / Talablar Tavsifi')),
                ('commitment_type', models.CharField(choices=[('To‘liq stavka', 'To‘liq stavka'), ('Erkin grafik', 'Erkin grafik'), ('Yarim stavka', 'Yarim stavka'), ('Loyiha asosida', 'Loyiha asosida')], default='Erkin grafik', max_length=50, verbose_name='Ish Grafigi')),
                ('faculty', models.CharField(default='IT yoki Fizika-matematika', max_length=150, verbose_name='Tavsiya Qilingan Fakultet')),
                ('contact_telegram', models.CharField(max_length=100, verbose_name='Aloqa Uchun Telegram (@username)')),
                ('is_open', models.BooleanField(default=True, verbose_name='Vakansiya Ochiqmi?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Hammuassis Vakansiyasi',
                'verbose_name_plural': '9. Hammuassis (Co-Founder) Vakansiyalari',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Mentor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Mentor F.I.Sh')),
                ('title', models.CharField(max_length=200, verbose_name='Lavozimi / Mutaxassisligi')),
                ('organization', models.CharField(default='Navoiy davlat universiteti', max_length=200, verbose_name='Tashkilot / Kompaniya')),
                ('bio', models.TextField(verbose_name='Qisqacha Tarjimai Hol (Bio)')),
                ('avatar', models.URLField(max_length=500, verbose_name='Rasm URL')),
                ('expertise', models.JSONField(default=list, help_text='["AI & ML", "Pitch Deck"]', verbose_name='Ixtisoslik Sohalari (JSON massiv)')),
                ('available_slots', models.JSONField(default=list, help_text='["Seshanba 15:00", "Payshanba 16:00"]', verbose_name='Bo‘sh Vaqt Oraliqlari (JSON massiv)')),
                ('rating', models.DecimalField(decimal_places=1, default=5.0, max_digits=3, verbose_name='Reyting (1-5)')),
                ('reviews_count', models.PositiveIntegerField(default=0, verbose_name='Taqrizlar Soni')),
                ('telegram', models.CharField(blank=True, max_length=100, verbose_name='Telegram Profili (@username)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faolmi?')),
            ],
            options={
                'verbose_name': 'Mentor / Ekspert',
                'verbose_name_plural': '8. Mentorlar va Ekspertlar',
                'ordering': ['-rating', 'name'],
            },
        ),
        migrations.CreateModel(
            name='NewsArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Sarlavha')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Slug (URL uchun)')),
                ('category', models.CharField(choices=[('Akseleratsiya', '🚀 Akseleratsiya'), ('Grantlar', '💰 Grantlar'), ('Hamkorlik', '🤝 Hamkorlik'), ('Hakatonlar', '🏆 Hakatonlar'), ('Universitet', '🏛️ Universitet'), ('Investitsiya', '📈 Investitsiya')], default='Akseleratsiya', max_length=50, verbose_name='Kategoriya')),
                ('excerpt', models.TextField(verbose_name='Qisqa Anons (Excerpt)')),
                ('content', models.TextField(verbose_name='Batafsil Matn')),
                ('cover_image', models.URLField(max_length=500, verbose_name='Muqova Rasmi URL')),
                ('author_name', models.CharField(default='NavDU Axborot xizmati', max_length=150, verbose_name='Muallif F.I.Sh')),
                ('author_role', models.CharField(default='Matbuot kotibi', max_length=150, verbose_name='Muallif Lavozimi')),
                ('date_str', models.CharField(default='12 Mart, 2026', max_length=50, verbose_name='Sana (ko‘rinadigan)')),
                ('read_time', models.CharField(default='3 daqiqa', max_length=30, verbose_name='O‘qish Vaqti')),
                ('featured', models.BooleanField(default=False, verbose_name='Asosiy Yangilikmi? (Featured)')),
                ('views_count', models.PositiveIntegerField(default=0, verbose_name='Ko‘rishlar Soni')),
                ('likes_count', models.PositiveIntegerField(default=0, verbose_name='Yoqtirishlar (Likes)')),
                ('tags', models.JSONField(blank=True, default=list, verbose_name='Teglar (JSON massiv)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Yangilik / Press-reliz',
                'verbose_name_plural': '7. Yangiliklar va Matbuot',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PlaybookGuide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('G‘oya', '💡 G‘oya (Idea Validation)'), ('MVP', '🛠️ MVP (Prototip)'), ('Grantlar', '💰 Grantlar va Fondlar'), ('Pitch', '🎤 Pitch va Taqdimot'), ('Yuridik', '⚖️ Yuridik va Ro‘yxatdan o‘tish')], default='G‘oya', max_length=50, verbose_name='Qo‘llanma Bo‘limi')),
                ('title', models.CharField(max_length=255, verbose_name='Qo‘llanma Sarlavhasi')),
                ('read_time', models.CharField(default='6 daqiqa', max_length=30, verbose_name='O‘qish Vaqti')),
                ('summary', models.TextField(verbose_name='Qisqa Mazmuni')),
                ('author', models.CharField(max_length=150, verbose_name='Muallif / Mentor F.I.Sh')),
                ('author_role', models.CharField(max_length=150, verbose_name='Muallif Lavozimi')),
                ('key_takeaway', models.TextField(verbose_name='Asosiy Xulosa (Oltin Qoida)')),
                ('checklist', models.JSONField(default=list, verbose_name='Tekshiruv Ro‘yxati (Checklist, JSON massiv)')),
                ('detailed_content', models.JSONField(default=list, verbose_name='Batafsil Paragraflar (JSON massiv)')),
                ('template_download_url', models.URLField(blank=True, max_length=500, verbose_name='Yuklab Olish Shablon Havolasi')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib Raqami')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faolmi?')),
            ],
            options={
                'verbose_name': 'Playbook Qo‘llanmasi',
                'verbose_name_plural': '11. Startup Playbook Qo‘llanmalari',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Hikoya Sarlavhasi')),
                ('excerpt', models.TextField(verbose_name='Qisqa Anons')),
                ('content', models.TextField(verbose_name='Batafsil Muvaffaqiyat Tarixi')),
                ('author_name', models.CharField(max_length=150, verbose_name='Asoschi F.I.Sh')),
                ('author_role', models.CharField(max_length=150, verbose_name='Lavozimi / Roli')),
                ('author_avatar', models.URLField(max_length=500, verbose_name='Muallif Rasmi URL')),
                ('startup_name', models.CharField(max_length=150, verbose_name='Startap Nomi')),
                ('date_str', models.CharField(default='02.03.2026', max_length=50, verbose_name='Sana (matn)')),
                ('read_time', models.CharField(default='4 daqiqa', max_length=30, verbose_name='O‘qish Vaqti')),
                ('likes', models.PositiveIntegerField(default=0, verbose_name='Layklar Soni')),
                ('comments_count', models.PositiveIntegerField(default=0, verbose_name='Izohlar Soni')),
                ('tags', models.JSONField(blank=True, default=list, verbose_name='Teglar (JSON massiv)')),
                ('cover_image', models.URLField(blank=True, max_length=500, verbose_name='Muqova Rasmi (ixtiyoriy)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Startap Hikoyasi',
                'verbose_name_plural': '10. Muvaffaqiyat Hikoyalari (Blog)',
                'ordering': ['-created_at'],
            },
        ),
    ]
