# Generated by Django 5.1.4 on 2026-09-03 06:55

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('bio', models.CharField(blank=True, max_length=500)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='public/avatars/%Y/%m/')),
                ('role', models.CharField(choices=[('applicant', 'Arizachi'), ('admin', 'Admin'), ('superadmin', 'Superadmin'), ('investor', 'Investor')], default='applicant', max_length=20)),
                ('email_kind', models.CharField(choices=[('university', '@nsuni.uz'), ('personal', 'Shaxsiy'), ('unknown', "Noma'lum")], default='unknown', max_length=20)),
                ('affiliation', models.CharField(blank=True, choices=[('student', 'Talaba'), ('master', 'Magistrant'), ('alumni', 'Bitiruvchi'), ('faculty', "O'qituvchi"), ('other', 'Boshqa')], max_length=20)),
                ('student_id', models.CharField(blank=True, max_length=32)),
                ('is_student_verified', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('locale', models.CharField(default='uz', max_length=5)),
                ('consent_pd_at', models.DateTimeField(blank=True, null=True)),
                ('consent_marketing_at', models.DateTimeField(blank=True, null=True)),
                ('faculty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='cms.faculty')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Foydalanuvchi',
                'verbose_name_plural': 'Foydalanuvchilar',
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='UserCapability',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('capability', models.CharField(choices=[('reviewer', 'Reviewer'), ('mentor', 'Mentor'), ('faculty', 'Faculty')], max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capabilities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_capabilities',
            },
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['role'], name='users_role_0ace22_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['is_active'], name='users_is_acti_847b48_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['student_id'], name='users_student_2d3a08_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email_kind'], name='users_email_k_0df3c4_idx'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(condition=models.Q(('is_student_verified', True), models.Q(('student_id', ''), _negated=True)), fields=('student_id',), name='uq_users_verified_student_id'),
        ),
        migrations.AddConstraint(
            model_name='usercapability',
            constraint=models.UniqueConstraint(fields=('user', 'capability'), name='uq_user_capability'),
        ),
    ]
