# Generated by Django 5.1.4 on 2026-09-04 05:56

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cms', '0003_galleryimage'),
        ('cohorts', '0002_initial'),
        ('teams', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeArticle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(unique=True)),
                ('title_uz', models.CharField(max_length=200)),
                ('body_uz', models.TextField(blank=True)),
                ('audience', models.CharField(choices=[('founder', 'Jamoa'), ('staff', 'Xodim')], default='founder', max_length=16)),
                ('is_published', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'ops_knowledge',
                'ordering': ['title_uz'],
            },
        ),
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.SlugField(max_length=32, unique=True)),
                ('name', models.CharField(max_length=160)),
                ('channel', models.CharField(choices=[('telegram', 'Telegram'), ('instagram', 'Instagram'), ('facebook', 'Facebook'), ('faculty', 'Fakultet'), ('event', 'Tadbir'), ('qr', 'QR'), ('mentor', 'Mentor'), ('referral', 'Referral'), ('other', 'Boshqa')], default='other', max_length=20)),
                ('destination', models.CharField(choices=[('apply', 'Ariza sahifasi'), ('telegram', 'Telegram bot')], default='apply', max_length=20)),
                ('note', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('clicks', models.PositiveIntegerField(default=0)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaigns_created', to=settings.AUTH_USER_MODEL)),
                ('faculty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaigns', to='cms.faculty')),
            ],
            options={
                'db_table': 'ops_campaigns',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CampaignHit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=300)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hits', to='ops.campaign')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaign_hits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ops_campaign_hits',
            },
        ),
        migrations.CreateModel(
            name='InvestorInterest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('investor_name', models.CharField(blank=True, max_length=150)),
                ('status', models.CharField(choices=[('invited', 'Taklif'), ('attended', 'Keldi'), ('interested', 'Qiziqdi'), ('intro', 'Intro berildi'), ('passed', 'O‘tdi')], default='invited', max_length=16)),
                ('notes', models.TextField(blank=True)),
                ('investor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interests', to='cms.investor')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investor_interests', to='teams.team')),
            ],
            options={
                'db_table': 'ops_investor_interests',
            },
        ),
        migrations.CreateModel(
            name='OfficeHour',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('summary', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('open', 'Ochiq'), ('booked', 'Band'), ('done', 'O‘tdi'), ('cancelled', 'Bekor')], default='open', max_length=16)),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='office_hours', to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='office_hours', to='teams.team')),
            ],
            options={
                'db_table': 'ops_office_hours',
                'ordering': ['starts_at'],
            },
        ),
        migrations.CreateModel(
            name='OpsTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('todo', 'Navbat'), ('doing', 'Jarayon'), ('done', 'Tayyor')], default='todo', max_length=12)),
                ('area', models.CharField(choices=[('content', 'Kontent'), ('event', 'Tadbir'), ('faculty', 'Dekanat'), ('mentor', 'Mentor'), ('tech', 'Texnik'), ('demo', 'Demo Day'), ('other', 'Boshqa')], default='other', max_length=20)),
                ('due_at', models.DateTimeField(blank=True, null=True)),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ops_tasks', to=settings.AUTH_USER_MODEL)),
                ('season', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ops_tasks', to='cohorts.season')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ops_tasks', to='teams.team')),
            ],
            options={
                'db_table': 'ops_tasks',
            },
        ),
        migrations.CreateModel(
            name='ProgramWeek',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('week', models.PositiveSmallIntegerField()),
                ('slug', models.SlugField(blank=True, max_length=64)),
                ('title_uz', models.CharField(max_length=160)),
                ('title_en', models.CharField(blank=True, max_length=160)),
                ('outcome_uz', models.TextField(blank=True)),
                ('starts_at', models.DateTimeField(blank=True, null=True)),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ops_weeks', to='cohorts.season')),
            ],
            options={
                'db_table': 'ops_program_weeks',
                'ordering': ['week'],
            },
        ),
        migrations.CreateModel(
            name='Deliverable',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('submitted', 'Topshirildi'), ('late', 'Kechikdi'), ('missing', 'Yo‘q')], default='pending', max_length=16)),
                ('url', models.URLField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliverables', to='teams.team')),
                ('week', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliverables', to='ops.programweek')),
            ],
            options={
                'db_table': 'ops_deliverables',
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('present', models.BooleanField(default=True)),
                ('notes', models.CharField(blank=True, max_length=240)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance', to='teams.team')),
                ('week', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance', to='ops.programweek')),
            ],
            options={
                'db_table': 'ops_attendance',
            },
        ),
        migrations.CreateModel(
            name='SurveyResponse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('session', 'Sessiya'), ('nps', 'NPS')], default='session', max_length=16)),
                ('score', models.PositiveSmallIntegerField()),
                ('comment', models.TextField(blank=True)),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='surveys', to='cohorts.season')),
                ('week', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='surveys', to='ops.programweek')),
            ],
            options={
                'db_table': 'ops_surveys',
            },
        ),
        migrations.CreateModel(
            name='TeamWeeklyUpdate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('body', models.TextField()),
                ('url', models.URLField(blank=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='weekly_updates_written', to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_updates', to='teams.team')),
                ('week', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='ops.programweek')),
            ],
            options={
                'db_table': 'ops_weekly_updates',
            },
        ),
        migrations.CreateModel(
            name='DemoDaySlot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('speaker', models.CharField(blank=True, max_length=150)),
                ('duration_sec', models.PositiveSmallIntegerField(default=180)),
                ('deck_ok', models.BooleanField(default=False)),
                ('demo_ok', models.BooleanField(default=False)),
                ('video_ok', models.BooleanField(default=False)),
                ('tech_checked', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demo_slots', to='cohorts.season')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demo_slots', to='teams.team')),
            ],
            options={
                'db_table': 'ops_demo_slots',
                'ordering': ['order', 'created_at'],
                'constraints': [models.UniqueConstraint(fields=('season', 'team'), name='uq_ops_demo_slot_team')],
            },
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(max_length=254)),
                ('name', models.CharField(blank=True, max_length=150)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('idea', models.CharField(blank=True, max_length=280)),
                ('notes', models.TextField(blank=True)),
                ('affiliation', models.CharField(blank=True, max_length=20)),
                ('status', models.CharField(choices=[('new', 'Yangi'), ('contacted', 'Bog‘lanildi'), ('nurturing', 'Yetaklanmoqda'), ('qualified', 'Mos'), ('converted', 'Arizaga o‘tdi'), ('lost', 'Yo‘qotildi'), ('next_season', 'Keyingi mavsum')], default='new', max_length=20)),
                ('source', models.CharField(choices=[('site', 'Sayt'), ('telegram', 'Telegram'), ('instagram', 'Instagram'), ('facebook', 'Facebook'), ('faculty', 'Fakultet'), ('event', 'Tadbir'), ('mentor', 'Mentor'), ('qr', 'QR'), ('referral', 'Referral'), ('ingest', 'Tizim'), ('admin', 'Admin'), ('other', 'Boshqa')], default='admin', max_length=20)),
                ('next_contact_at', models.DateTimeField(blank=True, null=True)),
                ('converted_at', models.DateTimeField(blank=True, null=True)),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='ops.campaign')),
                ('converted_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_leads', to=settings.AUTH_USER_MODEL)),
                ('faculty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='cms.faculty')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_leads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ops_leads',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='ops_leads_status_74cdb6_idx'), models.Index(fields=['email'], name='ops_leads_email_b6decf_idx'), models.Index(fields=['source'], name='ops_leads_source_4a39f2_idx')],
            },
        ),
        migrations.CreateModel(
            name='MentorAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('primary', 'Asosiy'), ('advisor', 'Maslahatchi')], default='primary', max_length=16)),
                ('notes', models.TextField(blank=True)),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mentor_assignments', to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentor_assignments', to='teams.team')),
            ],
            options={
                'db_table': 'ops_mentor_assignments',
                'constraints': [models.UniqueConstraint(fields=('team', 'mentor'), name='uq_ops_mentor_team')],
            },
        ),
        migrations.AddConstraint(
            model_name='programweek',
            constraint=models.UniqueConstraint(fields=('season', 'week'), name='uq_ops_week_season'),
        ),
        migrations.AddConstraint(
            model_name='deliverable',
            constraint=models.UniqueConstraint(fields=('week', 'team'), name='uq_ops_deliverable_week_team'),
        ),
        migrations.AddConstraint(
            model_name='attendance',
            constraint=models.UniqueConstraint(fields=('week', 'team'), name='uq_ops_attendance_week_team'),
        ),
    ]
