# Generated by Django 5.1.4

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_investor'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='public/cms/gallery/%Y/%m/')),
                ('caption_uz', models.CharField(blank=True, max_length=200)),
                ('caption_en', models.CharField(blank=True, max_length=200)),
                ('placement', models.CharField(
                    blank=True,
                    choices=[
                        ('', 'Faqat galereya'),
                        ('about', 'About blok'),
                        ('demo', 'Demo Day'),
                        ('apply', 'Ariza banner'),
                        ('og', 'Open Graph'),
                    ],
                    default='',
                    max_length=20,
                )),
                ('show_in_gallery', models.BooleanField(default=True)),
                ('is_published', models.BooleanField(default=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Galereya rasmi',
                'verbose_name_plural': 'Galereya rasmlari',
                'db_table': 'gallery_images',
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
