# Generated by Django 5.1.4 on 2026-09-03 06:55

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cohorts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StartupPortfolio',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(unique=True)),
                ('is_published', models.BooleanField(default=False)),
                ('summary_uz', models.TextField(blank=True)),
                ('summary_en', models.TextField(blank=True)),
                ('website', models.URLField(blank=True)),
                ('traction_public', models.JSONField(blank=True, default=dict)),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='portfolio', to='cohorts.season')),
            ],
            options={
                'db_table': 'startup_portfolio',
            },
        ),
    ]
