# Generated by Django 5.1.4 on 2026-09-03 06:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cohorts', '0001_initial'),
        ('portfolio', '0001_initial'),
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='startupportfolio',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_entries', to='teams.team'),
        ),
        migrations.AddField(
            model_name='startupportfolio',
            name='track',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cohorts.track'),
        ),
        migrations.AddIndex(
            model_name='startupportfolio',
            index=models.Index(fields=['season', 'is_published'], name='startup_por_season__83205c_idx'),
        ),
        migrations.AddIndex(
            model_name='startupportfolio',
            index=models.Index(fields=['track', 'is_published'], name='startup_por_track_i_ec1a2c_idx'),
        ),
        migrations.AddConstraint(
            model_name='startupportfolio',
            constraint=models.UniqueConstraint(fields=('team', 'season'), name='uq_portfolio_team_season'),
        ),
    ]
