# Generated by Django 5.1.15 on 2026-09-13 13:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Tadbir Nomi')),
                ('type', models.CharField(choices=[('Hakaton', '🏆 Hakaton'), ('Seminar', '🎤 Seminar / Trening'), ('Demo Day', '🚀 Demo Day'), ('Meetup', '☕ Meetup'), ('Vebinar', '💻 Onlayn Vebinar')], default='Hakaton', max_length=50, verbose_name='Tadbir Turi')),
                ('date', models.CharField(max_length=100, verbose_name='Sana (masalan: 18-20 Oktyabr, 2026)')),
                ('time', models.CharField(max_length=100, verbose_name='Vaqti (masalan: 09:00 - 18:00)')),
                ('location', models.CharField(default='NavDU Bosh binosi, Kovorking zali', max_length=255, verbose_name='O‘tkazilish Joyi')),
                ('mode', models.CharField(choices=[('Oflayn', 'Oflayn (Universitet binosida)'), ('Onlayn', 'Onlayn (Zoom / Meet)'), ('Gibrid', 'Gibrid')], default='Oflayn', max_length=50, verbose_name='Formati')),
                ('prize', models.CharField(blank=True, help_text='Masalan: 60 000 000 so‘m', max_length=100, verbose_name='Mukofot Jamg‘armasi')),
                ('registration_deadline', models.CharField(max_length=100, verbose_name='Ro‘yxatdan O‘tish Oxirgi Muddati')),
                ('description', models.TextField(verbose_name='Tadbir Tavsifi va Qoidalari')),
                ('is_registration_open', models.BooleanField(default=True, verbose_name='Ro‘yxatdan O‘tish Ochiqmi?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Tadbir / Hakaton',
                'verbose_name_plural': '1. Tadbirlar va Hakatonlar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_id', models.CharField(max_length=50, unique=True, verbose_name='Chipta ID (Raqamli kod)')),
                ('participant_name', models.CharField(max_length=200, verbose_name='Qatnashuvchi F.I.Sh')),
                ('phone', models.CharField(max_length=30, verbose_name='Telefon Raqami')),
                ('telegram', models.CharField(max_length=100, verbose_name='Telegram (@username)')),
                ('faculty', models.CharField(max_length=150, verbose_name='Fakultet')),
                ('is_attended', models.BooleanField(default=False, verbose_name='Eshikda Skaner Qilinganmi? (Davomat)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ro‘yxatdan O‘tgan Vaqti')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='events.event', verbose_name='Tadbir')),
            ],
            options={
                'verbose_name': 'Raqamli QR Chipta',
                'verbose_name_plural': '2. Ro‘yxatdan O‘tganlar va Chiptalar',
                'ordering': ['-created_at'],
            },
        ),
    ]
