# Generated by Django 5.1.15 on 2026-09-13 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HeroSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('badge', models.CharField(default='Navoiy Davlat Universiteti', max_length=100, verbose_name='Kichik Badge')),
                ('title', models.CharField(help_text='Masalan: Inkubatsiya va Akseleratsiya', max_length=200, verbose_name='Asosiy Sarlavha')),
                ('title_accent', models.CharField(help_text='Masalan: Markazi', max_length=100, verbose_name='Rangli Urg‘u So‘z')),
                ('subtitle', models.CharField(default='G‘oyadan Investitsiyagacha • 45 Kunlik Dastur', max_length=255, verbose_name='Kichik Sarlavha')),
                ('description', models.TextField(verbose_name='Batafsil Tavsif')),
                ('image_url', models.URLField(max_length=500, verbose_name='Fon Rasmi URL manzili')),
                ('highlights', models.JSONField(default=list, help_text='JSON massiv ko‘rinishida: ["100+ o‘rinli Kovorking", "3D Prototyping", "$5,000 grantlar"]', verbose_name='Muhim Nuqtalar (Highlights)')),
                ('cta_text', models.CharField(default='Akseleratsiyaga ariza topshirish', max_length=100, verbose_name='Bosh Tugma Matni')),
                ('secondary_cta_text', models.CharField(default='Dastur haqida batafsil', max_length=100, verbose_name='Ikkinchi Tugma Matni')),
                ('cta_action', models.CharField(choices=[('apply', 'Akseleratsiyaga ariza topshirish'), ('events', 'Hakatonlar & Tadbirlar kalendari'), ('team', 'Talent Pool & Jamoa qidirish'), ('portfolio', 'Startaplar portfelini ko‘rish')], default='apply', max_length=50, verbose_name='Tugma Amal Yo‘nalishi')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ko‘rsatilish Tartibi')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faolmi?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Bosh Slayd',
                'verbose_name_plural': '1. Bosh Sahifa Slaydlari',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PartnerLogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Hamkor Nomi')),
                ('logo_svg_key', models.CharField(blank=True, help_text='SvgLogoNKMK, SvgLogoITPark...', max_length=50, verbose_name='SVG Ikonka Kaliti')),
                ('custom_logo_url', models.URLField(blank=True, max_length=500, verbose_name='Yoki Rasm URL havolasi')),
                ('website_url', models.URLField(blank=True, max_length=500, verbose_name='Hamkor Vebsayti')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartibi')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faolmi?')),
            ],
            options={
                'verbose_name': 'Hamkor Logotipi',
                'verbose_name_plural': '5. Hamkorlar Logotiplari (Marquee)',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='PlatformMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text='Masalan: Jami Jalb Qilingan', max_length=100, verbose_name='Ko‘rsatkich Nomi')),
                ('value', models.CharField(help_text='Masalan: $975,000 yoki 32+', max_length=50, verbose_name='Qiymat / Raqam')),
                ('subtitle', models.CharField(blank=True, max_length=150, verbose_name='Qo‘shimcha Izoh')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartibi')),
            ],
            options={
                'verbose_name': 'Platforma Statistikasi',
                'verbose_name_plural': '4. Bosh Sahifa Metrikalari',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SectionConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_key', models.CharField(choices=[('hero_slider', 'Bosh Slayder'), ('program_stages', 'Dastur Bosqichlari (45 kun)'), ('portfolio_section', 'Startaplar Katalogi & Leaderboard'), ('demo_day_section', 'Demo Day Natijalari'), ('news_section', 'Yangiliklar & Matbuot'), ('events_section', 'Hakatonlar & Tadbirlar'), ('talent_pool_section', 'Talent Pool & Hammuassislar'), ('playbook_section', 'Startup Playbook'), ('partners_marquee', 'Hamkorlar Marquee Aylanishi')], max_length=50, unique=True, verbose_name='Bo‘lim Turi')),
                ('custom_title', models.CharField(max_length=150, verbose_name='Admin Uchun Nomi')),
                ('is_visible', models.BooleanField(default=True, verbose_name='Saytda Ko‘rinsinmi?')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ko‘rsatilish Tartibi')),
            ],
            options={
                'verbose_name': 'Bo‘lim Tartibi va Ko‘rinishi',
                'verbose_name_plural': '2. Sayt Bo‘limlarini Boshqarish',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='TopTicker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('badge_text', models.CharField(default='NavDU 3-Mavsum', max_length=50, verbose_name='Badge Yozuvi')),
                ('message', models.CharField(max_length=255, verbose_name='E’lon Matni')),
                ('action_text', models.CharField(default='Ariza topshirish →', max_length=50, verbose_name='Tugma Matni')),
                ('action_url', models.CharField(default='#apply', max_length=100, verbose_name='Havola yoki Amal')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faolmi?')),
            ],
            options={
                'verbose_name': 'Tepa E’lon Banneri',
                'verbose_name_plural': '3. Tepa Mikro-Ticker Banneri',
            },
        ),
    ]
