# Generated by Django 5.1.15 on 2026-09-13 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layout', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Startup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Startap Nomi')),
                ('tagline', models.CharField(max_length=300, verbose_name='Shior / Qisqa Ta‘rif')),
                ('category', models.CharField(default='AI & EdTech', max_length=100, verbose_name='Kategoriya')),
                ('stage', models.CharField(default='MVP', max_length=50, verbose_name='Bosqich')),
                ('batch', models.CharField(default='3-Mavsum (2026)', max_length=100, verbose_name='Mavsum')),
                ('upvotes', models.PositiveIntegerField(default=0, verbose_name='Ovozlar Soni')),
                ('raised_amount', models.CharField(default='$0', max_length=50, verbose_name='Jalb Qilingan Investitsiya')),
                ('problem', models.TextField(blank=True, verbose_name='Muammo')),
                ('solution', models.TextField(blank=True, verbose_name='Yechim')),
                ('full_description', models.TextField(blank=True, verbose_name='To‘liq Tavsif')),
                ('logo', models.CharField(default='🚀', max_length=20, verbose_name='Logo (Emoji)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Rezident Startap',
                'verbose_name_plural': '6. Rezident Startaplar Katalogi',
                'ordering': ['-upvotes', '-created_at'],
            },
        ),
    ]
