# Generated by Django 5.1.15 on 2026-09-13 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layout', '0003_cofoundervacancy_mentor_newsarticle_playbookguide_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='playbookguide',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True, verbose_name='Slug (URL manzili)'),
        ),
        migrations.AddField(
            model_name='startup',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True, verbose_name='Slug (URL manzili)'),
        ),
        migrations.AddField(
            model_name='story',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True, verbose_name='Slug (URL manzili)'),
        ),
        migrations.AlterField(
            model_name='newsarticle',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True, verbose_name='Slug (URL uchun)'),
        ),
    ]
