# Generated by Django 5.1.4 on 2026-09-03 06:55

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('from_status', models.CharField(max_length=24)),
                ('to_status', models.CharField(max_length=24)),
                ('note', models.TextField(blank=True)),
                ('payload', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'db_table': 'application_events',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('screening', 'Screening'), ('interview_invited', 'Interview Invited'), ('interviewed', 'Interviewed'), ('accepted', 'Accepted'), ('waitlisted', 'Waitlisted'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn')], default='draft', max_length=24)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('problem', models.TextField(blank=True)),
                ('solution', models.TextField(blank=True)),
                ('stage', models.CharField(blank=True, choices=[('idea', 'G‘oya'), ('mvp', 'MVP'), ('traction', 'Traction'), ('revenue', 'Daromad')], max_length=32)),
                ('why_us', models.TextField(blank=True)),
                ('faculty_endorsement_name', models.CharField(blank=True, max_length=150)),
                ('demo_url', models.URLField(blank=True)),
                ('video_url', models.URLField(blank=True)),
                ('pitch_deck', models.FileField(blank=True, null=True, upload_to='private/applications/decks/%Y/%m/')),
                ('extra', models.JSONField(blank=True, default=dict)),
                ('faculty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications', to='cms.faculty')),
            ],
            options={
                'db_table': 'applications',
            },
        ),
    ]
