# Generated by Django 5.1.4 on 2026-09-03 06:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applications', '0001_initial'),
        ('cohorts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='cohorts.season'),
        ),
    ]
