# Generated by Django 5.1.4 on 2026-09-03 06:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applications', '0002_initial'),
        ('cohorts', '0001_initial'),
        ('teams', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='submitted_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_apps', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='application',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='teams.team'),
        ),
        migrations.AddField(
            model_name='application',
            name='track',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='cohorts.track'),
        ),
        migrations.AddField(
            model_name='applicationevent',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='applicationevent',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='applications.application'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['season', 'status'], name='application_season__e0adaa_idx'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['track', 'status'], name='application_track_i_e56c32_idx'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['faculty', 'status'], name='application_faculty_43c6e1_idx'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['submitted_at'], name='application_submitt_f3e3d7_idx'),
        ),
        migrations.AddConstraint(
            model_name='application',
            constraint=models.UniqueConstraint(fields=('season', 'team'), name='uq_app_season_team'),
        ),
    ]
