# Generated by Django 5.1.4 on 2026-09-03 06:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applications', '0003_initial'),
        ('reviews', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewevent',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reviewassignment',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='applications.application'),
        ),
        migrations.AddField(
            model_name='reviewassignment',
            name='assigned_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='review_assignments_made', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reviewassignment',
            name='reviewer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='review_assignments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reviewscore',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='applications.application'),
        ),
        migrations.AddField(
            model_name='reviewscore',
            name='assignment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='score', to='reviews.reviewassignment'),
        ),
        migrations.AddField(
            model_name='reviewscore',
            name='reviewer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='reviewassignment',
            constraint=models.UniqueConstraint(fields=('application', 'reviewer'), name='uq_review_assignment'),
        ),
        migrations.AddConstraint(
            model_name='reviewscore',
            constraint=models.UniqueConstraint(fields=('application', 'reviewer'), name='uq_review_score'),
        ),
        migrations.AddConstraint(
            model_name='reviewscore',
            constraint=models.CheckConstraint(condition=models.Q(('team_score__gte', 1), ('team_score__lte', 5)), name='ck_team_score'),
        ),
        migrations.AddConstraint(
            model_name='reviewscore',
            constraint=models.CheckConstraint(condition=models.Q(('problem_score__gte', 1), ('problem_score__lte', 5)), name='ck_problem_score'),
        ),
        migrations.AddConstraint(
            model_name='reviewscore',
            constraint=models.CheckConstraint(condition=models.Q(('feasibility_score__gte', 1), ('feasibility_score__lte', 5)), name='ck_feasibility_score'),
        ),
        migrations.AddConstraint(
            model_name='reviewscore',
            constraint=models.CheckConstraint(condition=models.Q(('university_fit_score__gte', 1), ('university_fit_score__lte', 5)), name='ck_fit_score'),
        ),
        migrations.AddConstraint(
            model_name='reviewscore',
            constraint=models.CheckConstraint(condition=models.Q(('traction_score__isnull', True), models.Q(('traction_score__gte', 1), ('traction_score__lte', 5)), _connector='OR'), name='ck_traction_score'),
        ),
    ]
