# Generated by Django 5.1.15 on 2026-09-13 13:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Ariza ID (Kodi)')),
                ('founder_name', models.CharField(max_length=200, verbose_name='F.I.Sh. (Asoschi)')),
                ('phone', models.CharField(max_length=30, verbose_name='Telefon Raqami')),
                ('email', models.EmailField(max_length=254, verbose_name='Email Manzili')),
                ('telegram_username', models.CharField(max_length=100, verbose_name='Telegram Profili (@username)')),
                ('telegram_chat_id', models.BigIntegerField(blank=True, null=True, verbose_name='Telegram Chat ID')),
                ('faculty', models.CharField(max_length=150, verbose_name='Fakultet')),
                ('course', models.CharField(max_length=50, verbose_name='Kurs')),
                ('team_size', models.PositiveIntegerField(default=1, verbose_name='Jamoa A’zolari Soni')),
                ('project_name', models.CharField(max_length=200, verbose_name='Startap Nomi')),
                ('category', models.CharField(max_length=100, verbose_name='Yo‘nalishi / Kategoriya')),
                ('stage', models.CharField(choices=[('Idea', 'G‘oya (Idea)'), ('MVP', 'Prototip (MVP)'), ('Traction', 'Dastlabki Mijozlar (Traction)'), ('Scaling', 'Kengayish (Scaling)')], default='MVP', max_length=50, verbose_name='Rivojlanish Bosqichi')),
                ('problem', models.TextField(verbose_name='Hal Qilinayotgan Muammo')),
                ('solution', models.TextField(verbose_name='Taklif Qilinayotgan Yechim')),
                ('target_market', models.CharField(max_length=255, verbose_name='Maqsadli Bozor Hajmi')),
                ('deck_url', models.URLField(blank=True, max_length=500, null=True, verbose_name='Pitch Deck Havolasi (Google Drive / Canva / PDF)')),
                ('status', models.CharField(choices=[('Kutilmoqda', '🟡 Kutilmoqda (Yangi)'), ('Ko‘rib chiqilmoqda', '🔵 Hakamlar ko‘rib chiqmoqda'), ('Intervyuga chaqirildi', '🟣 Suhbatga taklif qilindi'), ('Qabul qilindi', '🟢 Qabul qilindi (3-Mavsum Rezidenti)'), ('Rad etildi', '🔴 Rad etildi')], default='Kutilmoqda', max_length=50, verbose_name='Ariza Holati')),
                ('feedback', models.TextField(blank=True, null=True, verbose_name='Ekspert / Rektorat Rasmiy Xulosasi (Talabaga)')),
                ('otp_code', models.CharField(blank=True, max_length=10, verbose_name='Bir Martalik OTP Kodi')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Telegram orqali tasdiqlanganmi?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Topshirilgan Vaqti')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Oxirgi O‘zgarish')),
            ],
            options={
                'verbose_name': 'Akseleratsiya Arizasi',
                'verbose_name_plural': '1. 45 Kunlik Dastur Arizalari',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ApplicationEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evaluator_name', models.CharField(max_length=150, verbose_name='Ekspert / Mentor F.I.Sh')),
                ('idea_score', models.PositiveSmallIntegerField(default=5, verbose_name='G‘oya dolzarbligi (1-10)')),
                ('team_score', models.PositiveSmallIntegerField(default=5, verbose_name='Jamoa salohiyati (1-10)')),
                ('market_score', models.PositiveSmallIntegerField(default=5, verbose_name='Bozor hajmi (1-10)')),
                ('comments', models.TextField(blank=True, verbose_name='Ekspert Izohi va Tavsiyasi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='applications.application', verbose_name='Ariza')),
            ],
            options={
                'verbose_name': 'Hakam Bahosi',
                'verbose_name_plural': '2. Hakamlar Baholash Varaqalari',
            },
        ),
    ]
